/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2020-12-14 06:02:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.security.SecureRandom;
import java.math.BigInteger;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604972224048L));
    _jspx_dependants.put("jar:file:/C:/workspace/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webPrac/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.math.BigInteger");
    _jspx_imports_classes.add("java.security.SecureRandom");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>eMoney Web 실습</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 네이버 로그인 연동 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery & bootstrap -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/inc/asset.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- RSA -->\r\n");
      out.write("<script src=\"resources/js/rsa/jsbn.js\"></script>\r\n");
      out.write("<script src=\"resources/js/rsa/prng4.js\"></script>\r\n");
      out.write("<script src=\"resources/js/rsa/rng.js\"></script>\r\n");
      out.write("<script src=\"resources/js/rsa/rsa.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- wrapper -->\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- 여기부터 본문 복사 -->\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<div id=\"cont_inner\">\r\n");
      out.write("\t\t\t\t<div id=\"infobox\">\r\n");
      out.write("\t\t\t\t\t<form id=\"loginForm\" action=\"loginCheck.do\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<h3>로그인</h3>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idBox\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"idHiddenBox\" name=\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"pwBox\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"pwHiddenBox\" name=\"pw\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- submit btn -->\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"loginbox\" value=\"로그인\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"loginInputCheck();\")>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img width=\"120\" height=\"45\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 15px;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"http://static.nid.naver.com/oauth/small_g_in.PNG\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 공개키 설정에 필요한 값 -->\r\n");
      out.write("\t<input type=\"hidden\" id=\"modulusVal\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modulus }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"exponentVal\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exponent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t// 페이지 로딩 시 로그인 포커스\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t    $(\"#idBox\").focus();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tvar rsa = new RSAKey();\r\n");
      out.write("\tvar modulus = $(\"#modulusVal\").val();\r\n");
      out.write("\tvar exponent = $(\"#exponentVal\").val();\r\n");
      out.write("\trsa.setPublic(modulus, exponent);\r\n");
      out.write("\r\n");
      out.write("\tfunction loginInputCheck() {\r\n");
      out.write("\t    if ($(\"#idBox\").val() == \"\") {\r\n");
      out.write("\t\talert(\"아이디 입력을 확인해주세요\");\r\n");
      out.write("\t\t$(\"#idBox\").focus();\r\n");
      out.write("\t    } else if ($(\"#pwBox\").val() == \"\") {\r\n");
      out.write("\t\talert(\"비밀번호 입력을 확인해주세요\");\r\n");
      out.write("\t\t$(\"#pwBox\").focus();\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t\t// 암호화 후 전송\r\n");
      out.write("\t\talert($(\"#idBox\").val());\r\n");
      out.write("\t\talert($(\"#pwBox\").val());\r\n");
      out.write("\r\n");
      out.write("\t\tvar encrypedId = rsa.encrypt($(\"#idBox\").val());\r\n");
      out.write("\t\tvar encrypedPw = rsa.encrypt($(\"#pwBox\").val());\r\n");
      out.write("\r\n");
      out.write("\t\talert(encrypedId);\r\n");
      out.write("\t\talert(encrypedPw);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#idHiddenBox\").val(encrypedId);\r\n");
      out.write("\t\t$(\"#pwHiddenBox\").val(encrypedPw);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#loginForm\").submit();\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
